#!/usr/bin/env python3
"""Generate the Goose runtime config (.goose/config.yaml) from the AAIF source.

Goose reads a YAML config (extensions declared with `type: stdio`). The AAIF
source of truth is `.agents/runtime/goose.json`, which already uses Goose's
native extension schema. This script converts that JSON into the YAML file
Goose expects at `.goose/config.yaml`, and — importantly — resolves the `uv`
`--directory` argument to an absolute project path so Goose can launch the
MCP server regardless of its own working directory.

Usage:
    python scripts/generate-goose-config.py
"""
from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_JSON = PROJECT_ROOT / ".agents" / "runtime" / "goose.json"
GOOSE_DIR = PROJECT_ROOT / ".goose"
GOOSE_CONFIG = GOOSE_DIR / "config.yaml"

HEADER = [
    "# Generated by scripts/generate-goose-config.py - DO NOT EDIT.",
    "# Source of truth: .agents/runtime/goose.json (AAIF).",
    "# Re-run scripts/sync-agent-configs to regenerate.",
]


def _yaml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value)
    needs_quote = (
        text == ""
        or text != text.strip()
        or text[0] in "-!&*?|>%@`"
        or any(ch in text for ch in (" ", ":", "#", "[", "]", "{", "}", "'", '"'))
    )
    return f'"{text}"' if needs_quote else text


def _resolve_args(args: list[str], project_root: Path) -> list[str]:
    out = list(args)
    for i, arg in enumerate(out[:-1]):
        if arg == "--directory":
            target = Path(out[i + 1])
            if not target.is_absolute():
                out[i + 1] = str((project_root / target).resolve())
    return out


def _emit_extensions(extensions: dict, project_root: Path) -> list[str]:
    lines: list[str] = []
    for name, ext in extensions.items():
        lines.append(f"  {name}:")
        for key, val in ext.items():
            if key == "args":
                lines.append("    args:")
                for arg in _resolve_args(val, project_root):
                    lines.append(f"      - {_yaml_scalar(arg)}")
            else:
                lines.append(f"    {key}: {_yaml_scalar(val)}")
    return lines


def main() -> None:
    data = json.loads(RUNTIME_JSON.read_text(encoding="utf-8"))
    extensions = data.get("extensions", {})
    GOOSE_DIR.mkdir(parents=True, exist_ok=True)
    lines = [*HEADER, "extensions:"]
    lines += _emit_extensions(extensions, PROJECT_ROOT)
    GOOSE_CONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"已生成 Goose 配置: {GOOSE_CONFIG}")


if __name__ == "__main__":
    main()
